**Ялтанский Александр HW01**

In [34]:
import numpy as np

# создание из обычных списков 
a = np.array(list(range(1, 6)))
a

array([1, 2, 3, 4, 5])

In [69]:
# создание массивов с использованием методов
# создаёт массив с shape (4, 4) из рандомных чисел
empty = np.empty([3, 3])
# создаёт матрицу вандермонда на основе последовательности чисел и степени
b = np.vander(a, 5)
empty, b[:5]

(array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 7.80623720e-321],
        [0.00000000e+000, 0.00000000e+000, 1.24421265e-311]]),
 array([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1],
        [625, 125,  25,   5,   1]]))

In [70]:
# атрибут shape показывает размерность тензора
empty.shape, b.shape

((3, 3), (5, 5))

In [71]:
# dtype - тип массива
empty.dtype, b.dtype

(dtype('float64'), dtype('int64'))

In [88]:
# различные варианты обращения по срезам в массиве
print(b[1, 1]) # 1-я строка, 1-й столбец (счёт с нуля)
print(b[1:]) #все строки, начиная с 1-й
print(b[[2,3], [2, 3]]) # 2-й элемент из 2-й и 3-й элемент из 3-й строки

8
[[ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
[9 4]


In [100]:
print(b[2:4, 2:4]) #2 по 3 элемент из 2 по 3 строк
print(b[:,2]) #2-й элемент из всех строк

[[ 9  3]
 [16  4]]
[ 1  4  9 16 25]


In [ ]:
a = np.array([np.logspace(start=1, stop=2, num=5, base=np.exp(1)), np.logspace(start=1, stop=4, num=5, base=2)])
b = np.ones(a.shape) * 5
a, b

(array([[ 2.71828183,  3.49034296,  4.48168907,  5.75460268,  7.3890561 ],
        [ 2.        ,  3.36358566,  5.65685425,  9.51365692, 16.        ]]),
 array([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]))

In [ ]:
# применение векторных операций 
print(a + b) # сложение
print(a - b) # вычитание
print(a * b) # поэлементное умножение

[[ 7.71828183  8.49034296  9.48168907 10.75460268 12.3890561 ]
 [ 7.          8.36358566 10.65685425 14.51365692 21.        ]]
[[-2.28171817 -1.50965704 -0.51831093  0.75460268  2.3890561 ]
 [-3.         -1.63641434  0.65685425  4.51365692 11.        ]]
[[13.59140914 17.45171479 22.40844535 28.77301338 36.94528049]
 [10.         16.81792831 28.28427125 47.5682846  80.        ]]


In [ ]:
#и операций из мат.статистики
print(a.mean()) # среднее значение по массиву
print(np.median(a)) # медиана
print(np.average(a, axis=0)) # среднее значение по столбцам

[[ 2.71828183  3.49034296  4.48168907  5.75460268  7.3890561 ]
 [ 2.          3.36358566  5.65685425  9.51365692 16.        ]]
6.036806946172434
5.0692716599152225
[ 2.35914091  3.42696431  5.06927166  7.6341298  11.69452805]
